version: "3.8"
services:
  prometheus:
    build: "./prometheus"
    ports:
      - 9090:9090
  node-exporter:
    build: "./node-exporter"
    ports:
      - 9100:9100
  blackbox-exporter:
    build: "./blackbox-exporter"
    ports:
      - 9115:9115
  grafana:
    build: "./grafana"
    ports:
      - 3000:3000
