FROM grafana/grafana-oss:latest
ADD files/nodeexporter.yaml /etc/grafana/provisioning/dashboards/nodeexporter.yaml
ADD files/node-exporter.json /var/lib/grafana/dashboards/node-exporter.json
ADD files/prometheus.yaml /etc/grafana/provisioning/datasources/prometheus.yaml
